"""Add events table and HNSW indexes

Revision ID: 3ec45615212f
Revises: 5a748883f1d9
Create Date: 2026-07-17 14:11:57.474991

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ec45615212f"
down_revision: Union[str, Sequence[str], None] = "5a748883f1d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Events table (use raw SQL to avoid failure if SQLAlchemy already created it)
    op.execute("""
        CREATE TABLE IF NOT EXISTS events (
            id VARCHAR(36) NOT NULL,
            user_id VARCHAR(36),
            session_id VARCHAR(100) NOT NULL,
            event_type VARCHAR(50) NOT NULL,
            job_id VARCHAR(36),
            band VARCHAR(10),
            ab_variant VARCHAR(30),
            payload JSON,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_events_user_id ON events (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_events_session_id ON events (session_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_events_event_type ON events (event_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_events_created_at ON events (created_at)")

    # HNSW Index Tuning
    op.execute(
        "CREATE INDEX IF NOT EXISTS seeker_embedding_hnsw_idx ON seekers USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS job_embedding_hnsw_idx ON jobs USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);"
    )
    op.execute("DROP INDEX IF EXISTS seeker_embedding_idx;")
    op.execute("DROP INDEX IF EXISTS job_embedding_idx;")

    # ### auto-generated Alembic commands — made idempotent for fresh DBs ###
    # These columns were JSONB in the original local DB but JSON in the models.
    # On a fresh Supabase DB (created by rev 5a748883f1d9), they are already JSON,
    # so the ALTER TYPE is a no-op. Use raw SQL with a type check to skip gracefully.
    _jsonb_to_json = [
        ("conversations", "messages"),
        ("courses", "skills_taught"),
        ("gamification", "badges"),
        ("gamification", "quests_completed"),
        ("jobs", "responsibilities"),
        ("jobs", "required_skills"),
        ("jobs", "nice_to_have_skills"),
        ("matches", "results"),
        ("seekers", "preferred_regions"),
        ("seekers", "skills"),
        ("seekers", "experience"),
        ("seekers", "education"),
        ("skill_gaps", "missing_skills"),
        ("skill_gaps", "matching_skills"),
        ("skill_gaps", "recommended_courses"),
    ]
    for table, col in _jsonb_to_json:
        op.execute(f"""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = '{table}'
                      AND column_name = '{col}'
                      AND data_type = 'jsonb'
                ) THEN
                    ALTER TABLE {table} ALTER COLUMN {col} TYPE json USING {col}::text::json;
                END IF;
            END $$;
        """)

    # users.name: initial migration did NOT have this column.
    # Add it here if it doesn't exist.
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'users'
                  AND column_name = 'name'
            ) THEN
                ALTER TABLE users ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT '';
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS seeker_embedding_hnsw_idx;")
    op.execute("DROP INDEX IF EXISTS job_embedding_hnsw_idx;")

    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_session_id"), table_name="events")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_table("events")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),
    )
    op.alter_column(
        "skill_gaps",
        "recommended_courses",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "skill_gaps",
        "matching_skills",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "skill_gaps",
        "missing_skills",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "seekers",
        "education",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "seekers",
        "experience",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "seekers",
        "skills",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "seekers",
        "preferred_regions",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "matches",
        "results",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "nice_to_have_skills",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "required_skills",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "responsibilities",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "gamification",
        "quests_completed",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "gamification",
        "badges",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "skills_taught",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "messages",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
