"""Initial schema

Revision ID: 5a748883f1d9
Revises: 
Create Date: 2026-06-01 23:26:03.623705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5a748883f1d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('seeker_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_seeker_id'), 'applications', ['seeker_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('seeker_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('skills_taught', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('cost_idr', sa.Integer(), nullable=False),
    sa.Column('is_prakerja', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seeker_id', sa.String(length=36), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('badges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quests_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_seeker_id'), 'gamification', ['seeker_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_kind', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_subject_id'), 'matches', ['subject_id'], unique=False)
    op.create_table('skill_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seeker_id', sa.String(length=36), nullable=False),
    sa.Column('target_job_id', sa.String(length=36), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matching_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gap_severity', sa.String(length=20), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('recommended_courses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_readiness_months', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_seeker_id'), 'skill_gaps', ['seeker_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('npwp', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('verified', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_user_id'), 'employers', ['user_id'], unique=False)
    op.create_table('seekers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('nik_verified', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('preferred_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('salary_expectation_min', sa.Integer(), nullable=False),
    sa.Column('salary_expectation_max', sa.Integer(), nullable=False),
    sa.Column('open_to_remote', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekers_user_id'), 'seekers', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kbji_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education_min', sa.String(length=10), nullable=False),
    sa.Column('experience_years_min', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('remote_allowed', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.Column('salary_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_employer_id'), 'jobs', ['employer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_employer_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_seekers_user_id'), table_name='seekers')
    op.drop_table('seekers')
    op.drop_index(op.f('ix_employers_user_id'), table_name='employers')
    op.drop_table('employers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skill_gaps_seeker_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    op.drop_index(op.f('ix_matches_subject_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_gamification_seeker_id'), table_name='gamification')
    op.drop_table('gamification')
    op.drop_table('courses')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_applications_seeker_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('ai_logs')
    # ### end Alembic commands ###
